
%%
filename = [pwd '\_results\tableOfResults', networkName, '.xlsx'];
sheet = 'Stats';

% Check if the file is there, and, if yes, overwrite
% We need this because in an older version we were writing to different
% cells (and these would thus still be in the sheet)

%try
%    t = xlsread(filename);
%catch err
%    if ~isempty(t)
%        xlswrite(filename,zeros(size(t))*nan, sheet);
%    end
%end
%%
if exist(filename,'file')==2
  delete(filename) ;
end

%% Header row

% In case you want to define a different set of reported approaches instead
% of those computed in the horseMaster
%approachesList = {...
   % 'orig',...
  %  'maxe',...
    %'anan',...
   % 'bara',...
  %  'dreh',...
 %   'mast2',...
%    'batt'};
%'hala',...

approachesList;

xlRange = 'D1';

xlswrite(...
    filename,...
    approachesList,...
    sheet,...
    xlRange)

%% Header column

xlswrite(...
    filename,...
    {'Statistics'},...
    sheet,...
    'A2')

statistics = {...
    '# of links'; ...
    'Density'; ...
    'Avg Degree'; ...
    'Med Degree'; ...
    'Assortativity'; ...
    'Clustering'; ...
    'Lender Dep'; ...
    'Borrower Dep'; ...
    'Mean HHI Assets'; ...                  % New added values
    'Median HHI Assets'; ...                % New added values
    'Mean HHI Liabilities'; ...             % New added values
    'Median HHI Liabilities'; ...           % New added values
    'Core Size (% banks)';...
    'Error score(% links)'};

xlswrite(...
    filename,...
    statistics,...
    sheet,...
    'B3')

SimilarityStartRow = 2 + numel(statistics) + 1;

xlswrite(...
    filename,...
    {'Similarity'},...
    sheet,...
    strcat('A', num2str(SimilarityStartRow)))

row = SimilarityStartRow + 1;
similarities ={...
    'Hamming';...
    'Jaccard';...
    'Cosine';...
    'Jensen'};

xlswrite(...
    filename,...
    similarities,...
    sheet,...
    strcat('B', num2str(row)))

ConfusionStartRow = SimilarityStartRow + numel(similarities)+1;
xlswrite(...
    filename,...
    {'Confusion Matrix'},...
    sheet,...
    strcat('A', num2str(ConfusionStartRow)))

confusionMatrix = {...
    'True Positives';...
    'True Negatives';...
    'False Positives';...
    'False Negatives';...
    'Accuracy'};

row = ConfusionStartRow + 1;
xlswrite(...
    filename,...
    confusionMatrix,...
    sheet,...
    strcat('B', num2str(row)))

DebtRankStartRow = ConfusionStartRow + numel(confusionMatrix) + 1;
xlswrite(...
    filename,...
    {'DebtRank'},...
    sheet,...
    strcat('A', num2str(DebtRankStartRow)))

debtRanks ={...
	'Sum DR';...				% New computed metrics
	'Avg DR';...				% New computed metrics
	'Sum DR Loss';...			% New computed metrics
	'Avg DR Loss';...			% New computed metrics
	'Top 1';...
    'Top 3';...
    'Correlation';...
    'Overlap 1';...
    'Overlap 3'};

row  = DebtRankStartRow + 1;
xlswrite(...
    filename,...
    debtRanks,...
    sheet,...
    strcat('B', num2str(row)))

LiquidityStartRow = DebtRankStartRow + numel(debtRanks) + 1;
xlswrite(...
    filename,...
    {'Liquidity'},...
    sheet,...
    strcat('A', num2str(LiquidityStartRow)))

liqShortfall = {...
    'Shortfall'};

row = LiquidityStartRow + 1;

xlswrite(...
    filename,...
    liqShortfall,...
    sheet,...
    strcat('B', num2str(row)))

% One collumn for each of the approachesList
column = ['D';'E';'F';'G';'H';'I';'J';'K'];



%% Format statistics

statisticsList = {...
    'Links',...
    'Density',...
    'MeanDeg',...
    'MedoDeg',...
    'SymPearson',...
    'Cmit',...
    'LendDep',...
    'BoroDep',...
    'MeanHHIAsset',...                      % New added values
    'MedianHHIAsset',...                    % New added values
    'MeanHHILiab',...                       % New added values
    'MedianHHILiab',...                     % New added values
    'coresize',...
    'score'};

% Iman: in the Debtrank section we have 
% median(1 * outputMatrices.(technique).(metric)),...
% Is that the way to colapse?

for i = 1 : length(approachesList)
    technique = approachesList{i};
    
    for j = 1 : length(statisticsList)
        metric = statisticsList{j};
        
        xlRange = [column(i) num2str(2+j)];
        report = num2str([ ...
            quantile(outputMatrices.(technique).(metric),0.1), ...
            median(outputMatrices.(technique).(metric)),...
            quantile(outputMatrices.(technique).(metric),0.9)]);
        
        xlswrite(...
            filename,...
            median(outputMatrices.(technique).(metric)),...
            sheet,...
            xlRange)
    end
end

%% Format similarity

similarityList = {...
    'hamming',...
    'jaccard',...
    'cosine',...
    'jensen'};

for i = 1 : length(approachesList)
    technique = approachesList{i};
    
    for j = 1 : length(similarityList)
        metric = similarityList{j};
        
        xlRange = [column(i) num2str(SimilarityStartRow+j)];
        xlswrite(...
            filename,...
            median(outputMatrices.(technique).similarity.(metric)),...
            sheet,...
            xlRange)
    end
end

%% Format Confusion Matrix

confusionMatrixList = {...
    'truePositives',...
    'trueNegatives',...
    'falsePositives',...
    'falseNegatives',...
    'accuracy'};

for i = 1 : length(approachesList)
    technique = approachesList{i};
    
    for j = 1 : length(confusionMatrixList)
        metric = confusionMatrixList{j};
        
        xlRange = [column(i) num2str(ConfusionStartRow+j)];
        xlswrite(...
            filename,...
            median(outputMatrices.(technique).confusionMatrix.(metric)),...
            sheet,...
            xlRange)
    end
end

%% Format DebtRank results


%% New statistics 

debtRankStatsList = {...
    'debtrank',...
    'debtrankloss'};

for i = 1 : length(approachesList)
    technique = approachesList{i};
    k=0;    
    for j = 1 : length(debtRankStatsList)
        metric = debtRankStatsList{j};
        
        xlRange = [column(i) num2str(DebtRankStartRow+j+k)];
        xlswrite(...
            filename,...
            mean(nansum(outputMatrices.(technique).(metric),1)),...
            sheet,...
            xlRange)
        
        xlRange = [column(i) num2str(DebtRankStartRow+j+1+k)];
        xlswrite(...
            filename,...
            mean(nanmean(outputMatrices.(technique).(metric),1)),...
            sheet,...
            xlRange)        
        k=k+1;
    end
end

debtRankList = {...
    'top1',...
    'top3',...
    'corr',...
    'overlap1',...
    'overlap3'};

for i = 1 : length(approachesList)
    technique = approachesList{i};
    
    for j = 1 : length(debtRankList)
        metric = debtRankList{j};
        
        xlRange = [column(i) num2str(DebtRankStartRow+j+4)];
        xlswrite(...
            filename,...
            median(1 * outputMatrices.(technique).(metric)),...
            sheet,...
            xlRange)
    end
end

%% Format Liquidity results

LiquidityList = {...
    'liquidityShortfall'};

for i = 1 : length(approachesList)
    technique = approachesList{i};
    
    for j = 1 : length(LiquidityList)
        metric = LiquidityList{j};
        
        xlRange = [column(i) num2str(LiquidityStartRow+j)];
        xlswrite(...
            filename,...
            median(1 * outputMatrices.(technique).(metric)),...
            sheet,...
            xlRange)
    end
end