function M_anan = anancode(Assets, Liabilities, Density, Ensemble)

N = length(Assets);

%Redefine variables to be used in our code
totalInterbankAssets_vec        = Assets';     % marginals lending
totalInterbankLiabilities_vec   = Liabilities;    % marginals borrowing

run(['anan/input/inputs'])
%run([a{:} '/input/inputs'])

cidx = 0;

while cidx == 0
    convergedEstimatedInterbank_mat = zeros(N,N,draws);
    density_vec = zeros(1,draws);
    
    for dr = 1 : draws
        
        [~, ~, ...
            estimatedInterbank_mat, ...
            convergedInd] = ...
            simulatedAnnealing_fun(...
            epsilon,...
            theta, ...
            c,...
            assetsPenalty_vec,...
            liabilitiesPenalty_vec, ...
            zeros(N),...
            totalInterbankAssets_vec,...
            totalInterbankLiabilities_vec, ...
            lambda,...
            dlambda,...
            annealingTime,...
            stopVal,...
            stopIterations);
        
        if convergedInd == 1
            convergedEstimatedInterbank_mat(:, :, cidx + 1) = estimatedInterbank_mat;
            density_vec(cidx + 1) = 100* nnz(estimatedInterbank_mat)/(N*(N-1));
            cidx = cidx + 1;
        end
        
    end
end

if ~isempty(density_vec)
    [~, midx] = min(density_vec);
    M_anan = convergedEstimatedInterbank_mat(:, :, midx);
end